import {test,expect} from '@playwright/test';

test('notes can be added and edited offline in inventory and archive, without appearing in lists',async({page,context})=>{
 await page.goto('/_site/');await page.evaluate(()=>navigator.serviceWorker.ready);
 await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);
 await context.setOffline(true);
 await page.getByRole('link',{name:'豆を追加'}).click();
 await page.getByLabel('豆名',{exact:true}).fill('備考テストの豆');
 await page.getByRole('radio',{name:'2',exact:true}).check();
 await page.getByLabel('焙煎日',{exact:true}).fill('2025-01-01');
 const notes='\n9/22 友人に譲渡\n甘み、花の香り </textarea><img src=x onerror=alert(1)>';
 await page.getByLabel('備考（任意）').fill(notes);
 await page.getByRole('button',{name:'登録',exact:true}).click();
 await expect(page.locator('.bean-group')).not.toContainText('友人に譲渡');
 await page.getByLabel('並び順').selectOption('oldest');
 await expect(page.locator('.bean-card')).not.toContainText('友人に譲渡');
 await page.locator('.bean-card').click();await expect(page.locator('.bean-notes')).toHaveText(notes);
 await expect(page.locator('.bean-notes img')).toHaveCount(0);
 expect(await page.locator('.bean-notes').evaluate(el=>getComputedStyle(el).whiteSpace)).toBe('pre-wrap');
 await page.getByRole('link',{name:'編集',exact:true}).click();await expect(page.getByLabel('備考（任意）')).toHaveValue(notes);
 await expect(page.locator('#bean-form img')).toHaveCount(0);
 await page.getByLabel('備考（任意）').fill(notes+'\n在庫で追記');
 await page.getByRole('button',{name:'保存',exact:true}).click();
 await page.getByRole('button',{name:'アーカイブへ移す',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'人に譲渡',exact:true}).click();
 await expect(page.getByText('アーカイブ日時',{exact:true})).toBeVisible();
 await expect(page.locator('.detail-grid').getByText('人に譲渡',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'アーカイブに戻る'}).click();
 await expect(page.locator('.bean-group')).not.toContainText('友人に譲渡');
 await page.locator('.batch-row').click();
 await page.getByRole('link',{name:'編集',exact:true}).click();await expect(page.getByLabel('備考（任意）')).toHaveValue(notes+'\n在庫で追記');await expect(page.getByLabel('終了区分')).toHaveValue('gifted');
 const archivedNotes='友人に譲渡済み\n香りがよかったとのこと';
 await page.getByLabel('備考（任意）').fill(archivedNotes);await page.getByRole('button',{name:'保存',exact:true}).click();
 await expect(page.locator('.bean-notes')).toHaveText(archivedNotes);
 await page.reload();await expect(page.locator('.bean-notes')).toHaveText(archivedNotes);
 await expect(page.getByText('アーカイブ日時',{exact:true})).toBeVisible();
 await page.setViewportSize({width:320,height:720});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/notes-detail-mobile.png',fullPage:true});
 await page.getByRole('link',{name:'編集',exact:true}).click();
 await page.screenshot({path:'test-results/notes-edit-mobile.png',fullPage:true});
 await page.getByLabel('備考（任意）').fill('');await page.getByRole('button',{name:'保存',exact:true}).click();
 await expect(page.locator('.bean-notes')).toHaveText('未記入');await page.reload();await expect(page.locator('.bean-notes')).toHaveText('未記入');
});
